export const SITE = {
  name: "Naija Tax Guide",
  companyName: "BMS SparkVision Hub",
  productOwnerLine: "A BMS SparkVision Hub product",
  slogan: "Clear Nigerian tax guidance for individuals, freelancers, and SMEs.",
  supportEmail: "support@naijataxguides.com",
  whatsappDisplay: "07034941158",
  whatsappInternational: "2347034941158",
  telegramBot: "naija-tax-guide-bot",
  businessRegistrationNo: "9480894",
  registrationDate: "10 April 2026",
  registeredNature: "Information service activities",
  registeredAddress: "32, Adebayo Street, Alakuko, Lagos State, Nigeria",
  domain: process.env.NEXT_PUBLIC_DOMAIN || "naijataxguides.com",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  apiBase: process.env.NEXT_PUBLIC_API_BASE || "",
  trustReviewDate: "30 June 2026",
};
