"use client";

import React, { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/auth";
import { apiJson, isApiError } from "@/lib/api";
import AppShell, { shellButtonPrimary, shellButtonSecondary } from "@/components/app-shell";
import WorkspaceSectionCard from "@/components/workspace-section-card";
import { Banner, formatDate } from "@/components/ui";
import { CardsGrid, SectionStack } from "@/components/page-layout";
import { useWorkspaceState } from "@/hooks/useWorkspaceState";

type LinkProvider = "wa" | "tg";
type Channel = "whatsapp" | "telegram";
type LinkGenerateResponse = { ok?:boolean; code?:string; expires_in_minutes?:number; expires_at?:string; provider?:string; account_id?:string; error?:string; deep_link?:string; link_url?:string; bot_url?:string; whatsapp_url?:string; telegram_url?:string };
type LinkUnlinkResponse = { ok?:boolean; unlinked?:boolean; reason?:string; error?:string };
type LinkState = { loading:boolean; error:string; success:string; code:string; expiresInMinutes:number|null; expiresAt:string; generatedAt:number|null; launchUrl:string };
type WorkspaceLimitsResponse = { ok?:boolean; entitlements?:{ plan?:{name?:string;plan_family?:string}; plan_family?:string|null } };
type ActivationSnapshot = { ok?:boolean; connected_channels?:Channel[]; active_channels?:Channel[]; paused_channels?:Channel[]; connected_count?:number; active_count?:number; selection_required?:boolean; max_active_channels?:number; error?:string };

function makeEmptyLinkState():LinkState{return{loading:false,error:"",success:"",code:"",expiresInMinutes:null,expiresAt:"",generatedAt:null,launchUrl:""};}
function safeText(value:unknown,fallback="Not shown"){const text=typeof value==="string"?value.trim():value==null?"":String(value).trim();return text||fallback;}
function truthyValue(value:unknown){if(typeof value==="boolean")return value;if(typeof value==="number")return value>0;if(typeof value==="string")return["1","true","yes","active","linked","enabled","verified"].includes(value.trim().toLowerCase());return false;}
function channelCardStyle():React.CSSProperties{return{border:"1px solid var(--border)",borderRadius:22,background:"var(--surface)",padding:22,display:"grid",gap:16,minWidth:0,width:"100%"};}
function itemStyle():React.CSSProperties{return{display:"grid",gap:4,padding:"0 0 12px",borderBottom:"1px solid var(--border)",minWidth:0};}
function itemLabelStyle():React.CSSProperties{return{fontSize:13,fontWeight:700,color:"var(--text-muted)"};}
function itemValueStyle():React.CSSProperties{return{fontSize:16,fontWeight:800,color:"var(--text)",minWidth:0,overflowWrap:"anywhere",wordBreak:"break-word",lineHeight:1.45};}
function actionGridStyle(min=180):React.CSSProperties{return{display:"grid",gridTemplateColumns:`repeat(auto-fit,minmax(min(100%, ${min}px),1fr))`,gap:12,width:"100%",minWidth:0,alignItems:"stretch"};}
function verificationLabel(v:boolean){return v?"Verified":"Not verified yet";}
function formatMinutesLabel(m:number|null){if(!m||m<=0)return"Code validity window unavailable.";return m===1?"Code expires in 1 minute.":`Code expires in ${m} minutes.`;}
function buttonStyleWithDisabledState(base:React.CSSProperties,disabled:boolean):React.CSSProperties{const b={...base,width:"100%",minWidth:0,justifyContent:"center",textAlign:"center" as const,whiteSpace:"normal" as const,lineHeight:1.35};return disabled?{...b,cursor:"not-allowed",background:"#e5e7eb",color:"#6b7280",border:"1px solid #d1d5db",boxShadow:"none"}:{...b,cursor:"pointer",opacity:1};}

function LinkCodePanel({provider,title,description,accountId,busy,locked,lockedMessage}:{provider:LinkProvider;title:string;description:string;accountId:string;busy:boolean;locked:boolean;lockedMessage:string}){
 const[state,setState]=useState<LinkState>(makeEmptyLinkState());const canGenerate=Boolean(accountId&&accountId!=="—")&&!busy&&!state.loading&&!locked;const hasCode=Boolean(state.code)&&!locked;const hasLaunchUrl=Boolean(state.launchUrl)&&!locked;
 async function handleGenerate(){if(locked){setState(p=>({...p,error:lockedMessage,success:""}));return;}if(!accountId||accountId==="—"){setState(p=>({...p,error:"Authenticated account reference is missing. Refresh the page and try again.",success:""}));return;}setState(p=>({...p,loading:true,error:"",success:""}));try{const res=await apiJson<LinkGenerateResponse>("/link/generate",{method:"POST",timeoutMs:20000,useAuthToken:false,query:{provider},body:{provider}});if(!res?.ok||!res?.code){setState(p=>({...p,loading:false,error:res?.error||`Could not generate a new ${title} link code.`,success:""}));return;}const returned=safeText(res.provider||"","").toLowerCase();if(returned&&returned!==provider){setState(p=>({...p,loading:false,error:`${title} generate returned wrong provider (${returned}).`,success:""}));return;}const launchUrl=safeText(res.deep_link||res.link_url||res.bot_url||res.whatsapp_url||res.telegram_url||"","");setState({loading:false,error:"",success:`${title} code generated successfully.`,code:String(res.code).toUpperCase(),expiresInMinutes:typeof res.expires_in_minutes==="number"?res.expires_in_minutes:null,expiresAt:safeText(res.expires_at||"",""),generatedAt:Date.now(),launchUrl});}catch(e){setState(p=>({...p,loading:false,error:isApiError(e)?e.message||`Request failed while generating ${title} link code.`:"Unexpected error while generating link code.",success:""}));}}
 async function handleCopy(){if(!state.code||locked)return;try{await navigator.clipboard.writeText(state.code);setState(p=>({...p,success:`${title} code copied.`,error:""}));}catch{setState(p=>({...p,success:"",error:"Copy failed. Please copy the code manually."}));}}
 const instruction=useMemo(()=>!state.code?"":provider==="tg"?`Send this code to the Telegram bot immediately: ${state.code}`:`Send this code to the official WhatsApp linking chat immediately: ${state.code}`,[provider,state.code]);
 return <div style={channelCardStyle()}><div><div style={{fontSize:14,color:"var(--text-muted)",fontWeight:700}}>{title}</div><div style={{fontSize:26,fontWeight:900}}>Live link setup</div><div style={{color:"var(--text-muted)",lineHeight:1.7}}>{description}</div></div><div style={itemStyle()}><div style={itemLabelStyle()}>Current Link Code</div><div style={{...itemValueStyle(),fontSize:28,letterSpacing:3}}>{state.code||"--------"}</div><div style={{color:"var(--text-muted)",fontSize:14}}>{state.code?formatMinutesLabel(state.expiresInMinutes):"No code generated yet."}</div>{instruction?<div>{instruction}</div>:null}</div><div style={itemStyle()}><div style={itemLabelStyle()}>Expires At</div><div style={itemValueStyle()}>{state.expiresAt?formatDate(state.expiresAt):"Not shown"}</div></div>{locked?<div style={{borderRadius:14,border:"1px solid #fed7aa",background:"#fff7ed",padding:12,color:"#9a3412",fontSize:14,lineHeight:1.6}}>{lockedMessage}</div>:null}<div style={actionGridStyle(170)}><button onClick={handleGenerate} disabled={!canGenerate} style={buttonStyleWithDisabledState(shellButtonPrimary(),!canGenerate)}>{state.loading?"Generating...":locked?`Generate ${title} Code Unavailable`:`Generate ${title} Code`}</button><button onClick={handleCopy} disabled={!hasCode} style={buttonStyleWithDisabledState(shellButtonSecondary(),!hasCode)}>Copy Code</button><button onClick={()=>state.launchUrl&&window.open(state.launchUrl,"_blank","noopener,noreferrer")} disabled={!hasLaunchUrl} style={buttonStyleWithDisabledState(shellButtonSecondary(),!hasLaunchUrl)}>Open Link</button></div>{state.success?<div style={{color:"#047857",fontWeight:700}}>{state.success}</div>:null}{state.error?<div style={{color:"#b91c1c",fontWeight:700}}>{state.error}</div>:null}</div>;
}

function UnlinkButton({provider,title,onDone}:{provider:LinkProvider;title:string;onDone:()=>Promise<void>|void}){const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");async function handleUnlink(){if(!window.confirm(`Permanently unlink ${title} from this website account? Pausing is normally enough when changing active channels.`))return;setBusy(true);setMsg("");try{const res=await apiJson<LinkUnlinkResponse>("/link/unlink",{method:"POST",timeoutMs:20000,useAuthToken:false,query:{provider},body:{provider}});setMsg(res?.ok?(res.unlinked?`${title} permanently unlinked.`:`${title} is not currently linked.`):(res?.error||"Could not unlink right now."));if(res?.ok)await onDone();}catch(e){setMsg(isApiError(e)?e.message||"Could not unlink right now.":"Could not unlink right now.");}finally{setBusy(false);}}return <div style={{display:"grid",gap:8}}><button onClick={handleUnlink} disabled={busy} style={buttonStyleWithDisabledState(shellButtonSecondary(),busy)}>{busy?`Unlinking ${title}...`:`Permanently unlink ${title}`}</button>{msg?<div style={{fontSize:13,color:"var(--text-muted)"}}>{msg}</div>:null}</div>;}

export default function ChannelsPage(){
 const{refreshSession}=useAuth();const{busy,load,accountId,activeNow,channelLinks}=useWorkspaceState({refreshSession,autoLoad:true,includeAccount:true,includeBilling:true,includeDebug:true,includeLinkStatus:true,loadingMessage:"Loading channel status..."});
 const[limitsData,setLimitsData]=useState<WorkspaceLimitsResponse|null>(null);const[limitsError,setLimitsError]=useState("");const[activation,setActivation]=useState<ActivationSnapshot|null>(null);const[activationError,setActivationError]=useState("");
 const loadLimits=useCallback(async()=>{try{setLimitsError("");setLimitsData(await apiJson<WorkspaceLimitsResponse>("/workspace/limits",{method:"GET",timeoutMs:20000,useAuthToken:false}));}catch(e){setLimitsError(isApiError(e)?e.message||"Unable to load channel entitlements.":"Unable to load channel entitlements.");}},[]);
 const loadActivation=useCallback(async()=>{try{setActivationError("");setActivation(await apiJson<ActivationSnapshot>("/channels/activation",{method:"GET",timeoutMs:20000,useAuthToken:false}));}catch(e){setActivationError(isApiError(e)?e.message||"Unable to load channel activation state.":"Unable to load channel activation state.");}},[]);
 const refreshPage=useCallback(async(message="Refreshing channel status...")=>{await Promise.all([load(message),loadLimits(),loadActivation()]);},[load,loadLimits,loadActivation]);
 useEffect(()=>{void Promise.all([loadLimits(),loadActivation()]);const refresh=()=>void loadActivation();window.addEventListener("ntg:channel-activation-changed",refresh);return()=>window.removeEventListener("ntg:channel-activation-changed",refresh);},[loadLimits,loadActivation]);
 const whatsappLinked=truthyValue(channelLinks?.whatsapp_linked||channelLinks?.whatsapp?.linked);const telegramLinked=truthyValue(channelLinks?.telegram_linked||channelLinks?.telegram?.linked);const whatsappVerified=truthyValue(channelLinks?.whatsapp_verified||channelLinks?.whatsapp?.verified||channelLinks?.whatsapp?.is_verified);const telegramVerified=truthyValue(channelLinks?.telegram_verified||channelLinks?.telegram?.verified||channelLinks?.telegram?.is_verified);
 const whatsappValue=safeText(channelLinks?.whatsapp?.value||channelLinks?.whatsapp?.phone||channelLinks?.whatsapp_number||"");const telegramValue=safeText(channelLinks?.telegram?.value||channelLinks?.telegram?.username||channelLinks?.telegram_username||"");const whatsappUpdatedAt=safeText(channelLinks?.whatsapp?.updated_at||channelLinks?.whatsapp_updated_at||"","");const telegramUpdatedAt=safeText(channelLinks?.telegram?.updated_at||channelLinks?.telegram_updated_at||"","");
 const planName=safeText(limitsData?.entitlements?.plan?.name||"Free","Free");const isFreePlan=(limitsData?.entitlements?.plan_family||limitsData?.entitlements?.plan?.plan_family||"free").toLowerCase().includes("free");
 const connected=activation?.connected_channels||[];const active=activation?.active_channels||[];const paused=activation?.paused_channels||[];const maxActive=activation?.max_active_channels??0;const activeCount=activation?.active_count??active.length;const connectedCount=activation?.connected_count??connected.length;const selectionRequired=Boolean(activation?.selection_required);const linkingLocked=maxActive<=0||selectionRequired||activeCount>=maxActive;
 const lockMessage=maxActive<=0?"Your current plan does not allow an external messaging channel.":selectionRequired?"Choose which preserved connection should remain active before linking another channel.":"Your active-channel allowance is currently in use. You do not need to unlink a preserved connection. Change the active channel above, or upgrade if you need more channels active at the same time.";
 const channelStatus=(channel:Channel,linked:boolean)=>!linked?"Not linked":active.includes(channel)?"Active":paused.includes(channel)?"Connected · Paused":selectionRequired?"Connected · awaiting selection":"Connected";
 const attentionBanner=!activeNow?{title:isFreePlan?"Free plan limits are active":"Subscription attention needed",subtitle:isFreePlan?"Your account can view channel status, but paid channel actions require an eligible plan.":"Your account can view channel status, but some actions may remain limited until subscription access is active."}:null;
 return <AppShell title="Channels" subtitle="Link, activate, pause, and manage supported messaging channels without losing preserved connections." actions={<button onClick={()=>void refreshPage()} disabled={busy} style={buttonStyleWithDisabledState(shellButtonPrimary(),busy)}>Refresh Status</button>}><SectionStack>
  {limitsError?<Banner tone="warn" title="Channel entitlement check needs attention" subtitle={limitsError}/>:null}{activationError?<Banner tone="warn" title="Channel activation check needs attention" subtitle={activationError}/>:null}
  {selectionRequired?<Banner tone="warn" title="Choose your active messaging channel" subtitle={`You have ${connectedCount} preserved connections but your plan allows ${maxActive} active external channel${maxActive===1?"":"s"}. Use the selector above. Excess connections remain saved and paused; unlinking is not required.`}/>:<Banner tone="good" title="Channel state is entitlement-aware" subtitle={`${activeCount} / ${maxActive} active · ${connectedCount} connected${paused.length?` · ${paused.length} paused`:""}. Connected and active are intentionally tracked separately.`}/>} 
  {attentionBanner?<Banner tone="warn" title={attentionBanner.title} subtitle={attentionBanner.subtitle}/>:null}
  <CardsGrid min={260}>{(["whatsapp","telegram"] as Channel[]).map(channel=>{const isWa=channel==="whatsapp";const linked=isWa?whatsappLinked:telegramLinked;const verified=isWa?whatsappVerified:telegramVerified;const value=isWa?whatsappValue:telegramValue;const updated=isWa?whatsappUpdatedAt:telegramUpdatedAt;const title=isWa?"WhatsApp":"Telegram";return <div key={channel} style={channelCardStyle()}><div><div style={{fontSize:14,color:"var(--text-muted)",fontWeight:700}}>{title}</div><div style={{fontSize:26,fontWeight:900}}>{channelStatus(channel,linked)}</div><div style={{color:"var(--text-muted)",lineHeight:1.7}}>{active.includes(channel)?"This connection is active and may consume NTG channel services.":paused.includes(channel)?"This connection is preserved but paused under the current entitlement. It does not need to be relinked later.":linked?"This connection is preserved on your account.":"This channel is not yet linked to your workspace."}</div></div><div style={itemStyle()}><div style={itemLabelStyle()}>Activation</div><div style={itemValueStyle()}>{channelStatus(channel,linked)}</div></div><div style={itemStyle()}><div style={itemLabelStyle()}>Verification</div><div style={itemValueStyle()}>{verificationLabel(verified)}</div></div><div style={itemStyle()}><div style={itemLabelStyle()}>{isWa?"Linked Number":"Linked Account"}</div><div style={itemValueStyle()}>{value}</div></div><div><div style={itemLabelStyle()}>Last Updated</div><div style={itemValueStyle()}>{updated?formatDate(updated):"Not shown"}</div></div>{linked?<UnlinkButton provider={isWa?"wa":"tg"} title={title} onDone={()=>refreshPage()}/>:null}</div>;})}</CardsGrid>
  <CardsGrid min={280}><LinkCodePanel provider="wa" title="WhatsApp" description="Generate a temporary WhatsApp linking code for this workspace." accountId={accountId} busy={busy} locked={linkingLocked} lockedMessage={lockMessage}/><LinkCodePanel provider="tg" title="Telegram" description="Generate a temporary Telegram linking code for this workspace." accountId={accountId} busy={busy} locked={linkingLocked} lockedMessage={lockMessage}/></CardsGrid>
  <WorkspaceSectionCard title="How channel limits work" subtitle="Active entitlement and durable connection are separate states."><div style={{display:"grid",gap:10,color:"var(--text-muted)",fontSize:14,lineHeight:1.8}}><div>1. A linked channel remains connected until you explicitly choose to permanently unlink it.</div><div>2. Your plan controls how many connected channels may be active at the same time.</div><div>3. After a downgrade, excess connections are paused rather than deleted.</div><div>4. If a choice is required, select the channel to keep active using the control above.</div><div>5. Upgrading can make preserved paused connections eligible for reactivation without relinking.</div></div></WorkspaceSectionCard>
 </SectionStack></AppShell>;
}
